
# Yaml Axis Plugin
# https://wiki.jenkins-ci.org/display/JENKINS/Yaml+Axis+Plugin
# This is a generated file produced by scripts/pr-ci-matrix.rb.

xcode_version:
 - 12.4
 - 12.5.1
 - 13.1
 - 13.2.1
 - 13.3.1
target:
 - swiftlint
 - swiftpm
 - swiftpm-debug
 - swiftpm-address
 - swiftpm-thread
 - swiftpm-ios
configuration:
 - N/A

exclude:

  - xcode_version: 12.4
    target: swiftlint

  - xcode_version: 12.5.1
    target: swiftlint

  - xcode_version: 13.1
    target: swiftlint

  - xcode_version: 13.2.1
    target: swiftlint

  - xcode_version: 12.5.1
    target: swiftpm

  - xcode_version: 13.1
    target: swiftpm

  - xcode_version: 13.2.1
    target: swiftpm

  - xcode_version: 12.4
    target: swiftpm-address

  - xcode_version: 12.5.1
    target: swiftpm-address

  - xcode_version: 13.1
    target: swiftpm-address

  - xcode_version: 13.2.1
    target: swiftpm-address

  - xcode_version: 12.4
    target: swiftpm-thread

  - xcode_version: 12.5.1
    target: swiftpm-thread

  - xcode_version: 13.1
    target: swiftpm-thread

  - xcode_version: 13.2.1
    target: swiftpm-thread

  - xcode_version: 12.4
    target: swiftpm-ios

  - xcode_version: 12.5.1
    target: swiftpm-ios

  - xcode_version: 13.1
    target: swiftpm-ios

  - xcode_version: 13.2.1
    target: swiftpm-ios
